spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_name
    username: username
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show_sql : true
    hiberate:
      ddl-auto: update

server:
  port: 8090